### PR TITLE
added h5py and tensorflow to IE

### PR DESCRIPTION
**Pull request by ThomasWollmann**

### CODE REVIEW

**Comment by ThomasWollmann** [comment]
"The log length has exceeded the limit of 4 MB (this usually means that the test suite is raising the same exception over and over)."

**Comment by bgruening** [comment]
conda has a `--quiet` option.

**Comment by ThomasWollmann** [comment]
Build job takes very long. Can't we separate the creation of the environments in separate repos/containers? Afterwards we can create several Jupyter flavors with R/Python/... environments.

**Comment by bgruening** [comment]
@ThomasWollmann any help here is welcome: https://github.com/bgruening/docker-jupyter-notebook/pull/16

**Comment by bgruening** [comment]
This should be fixed with the new image.
@ThomasWollmann I will be in HD the next two days.

**Comment by ThomasWollmann** [comment]
@bgruening Sorry I'm in Sydney. :/

**Comment by bgruening** [comment]
Cool, enjoy!

**Pull request closed without merging**
