### PR TITLE
New base image, new libraries

### PR DESCRIPTION
**Pull request by bgruening**
This is WIP. Any comments welcome.

### CODE REVIEW

**Comment by ThomasWollmann** [comment]
@bgruening why not split the image into images for every language? By adding more and more packages we will create a crazy big image.

**Comment by bgruening** [comment]
If I get more time I will do this, but this essentially means we need to maintain many images. This image is now based to a large degree on the official jupyter image.

What makes this image really big is 1) haskell support and 2) the low lever library which I add to make it possible to compile stuff on there own. Both are probably not used much. Should we drop this?

Also tensorflow would not be really needed in the image as you can just install it during runtime from conda.

I would like to keep R and Python in one image as you can create notebooks that contain both and you can pass R object to Python and so on ...

**Comment by ThomasWollmann** [comment]
I don't have a satisfying solution yet how we can solve this. I'll think about it.

**Comment by bgruening** [comment]
Thanks! I will take haskell out for now and we can build the image in under 45min I hope.

**Comment by bgruening** [comment]
The new image can be tested with `bgruening/docker-jupyter-notebook:new_base_image`. Any feedback welcome.

**Comment by bgruening** [comment]
@ThomasWollmann any feedback? Should we merge?

**Comment by ThomasWollmann** [comment]
I like it! :)

**Comment by bgruening** [comment]
And merged!

**Pull request merged**
