### PR TITLE
fix the magix button

### PR DESCRIPTION
**Pull request by bgruening**
and release 17.09 version

### CODE REVIEW

**Comment by natefoo** [comment]
Thanks @bgruening! The tags seem a bit messed up on quay.

**Comment by bgruening** [comment]
I will test this tm and let you know. This will end up on `master` and `17.09`. The `b17.09` will disappear.

**Comment by natefoo** [comment]
Oh ok, thanks!

**Comment by bgruening** [comment]
You can of course also test, but I guess you have more important things to do :)

**Comment by natefoo** [comment]
I will tomorrow as well! =)

**Comment by natefoo** [comment]
I was finally able to test this (it's in use on test.galaxyproject.org at the moment) and it works. Thanks!

**Pull request merged**
