### PR TITLE
Refactor to use gie-helpers

### PR DESCRIPTION
**Pull request by hexylena**

### CODE REVIEW

**Comment by hexylena** [comment]
> Error: MD5 sums mismatch for download: https://conda.anaconda.org/r/linux-64/r-boot-1.3_17-r3.2.2_0.tar.bz2 (210ce863c3d426eaf6111d14721a2dbe != 7cc08052f9d5ba6b131d8b3b6d915c77)

**Comment by bgruening** [comment]
Oh fun ...

**Comment by bgruening** [comment]
@erasche created a PR against your branch. What do you think about a travis test like this `docker run -i -t .. put --help` to check if we can run this script.

**Comment by hexylena** [comment]
sure, sounds good

**Pull request merged**
