### PR TITLE
Get testing

### PR DESCRIPTION
**Pull request by bgruening**
@erasche this is still needed to make it functional for R users or anyone that wants to use get/put from commandline. I was not able to test this functionality, but I hope it is working now.

If needed I can release a new version 16.01.1?

### CODE REVIEW

**Comment by hexylena** [comment]
:+1: looks good to me

**Comment by hexylena** [comment]
BTW I have R bindings for get/put, we should add those later.

**Comment by bgruening** [comment]
Yeah, let's get these bindings in as well! :)

**Comment by bgruening** [comment]
@erasche release is done and quay as well as the docker hub are building the image.
Thanks!

**Pull request merged**
